name: "dockerfile ci"
description: 'build image from dockerfile'
author: 'Calm Zhu'
inputs:
  subpath:
    description: "Source image full name"
    required: true
    default: '.'
  registry:
    description: "image registry host"
    required: false
    default: "docker.io"
  registry-user:
    description: "registry username"
    required: true
  registry-password:
    required: true
    description: "registry password"
  image-name:
    description: "name of target image"
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        image: tonistiigi/binfmt:latest
        platforms: linux/amd64
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker
        platforms: linux/amd64
    - name: Login to registory
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry-user }}
        password: ${{ inputs.registry-password }}
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: | # https://semver.org/
            ${{ inputs.image-name }}
        tags: | # https://momentjs.com/docs/#/displaying/format/
            type=ref,enable=true,suffix=-build${{ github.run_number }}-{{sha}},event=branch
            type=ref,prefix=pr-,suffix=-{{sha}},event=pr
            type=ref,event=branch
            type=raw,value=latest
        labels: | # https://github.com/opencontainers/image-spec/blob/master/annotations.md
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}/${{ inputs.subpath }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ${{ inputs.subpath }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

