name: "Docker image mirror push"
description: 'GitHub Action to mirror a docker image to other registry'
author: 'Calm Zhu'
inputs:
  source-image:
    description: "Source image full name"
    required: true
  target-registry:
    description: "Target image registry base url"
    required: true
  target-registry-user:
    description: "Target image registry username"
    required: true
  target-registry-password:
    required: true
    description: "Target image registry password"
  target-image-name:
    description: "name of target image"
    required: true
  tags:
    required: true
    description: "versions to mirror"

runs:
  using: 'composite'
  steps:
    - name: regctl login
      uses: regclient/actions/regctl-login@main
      with:
        registry: ${{ inputs.target-registry }}
        username: ${{ inputs.target-registry-user }}
        password: ${{ inputs.target-registry-password }}
    - name: docker hub login
      uses: regclient/actions/regctl-login@main
      with:
        registry: docker.io
        username: ${{ inputs.docker-io-user }}
        password: ${{ inputs.docker-io-token }}
    - shell: bash
      run: |
          for tag in `echo ${{ inputs.tags }}`
          do
              src=${{ inputs.source-image }}:$tag
              dst=${{ inputs.target-registry }}/${{ inputs.target-image-name }}:$tag
              regctl image copy $src $dst
          done
