name: simple dockerfile build
on:
  workflow_dispatch:
    inputs:
      subpath:
        description: "subpath of dockerfile"
        required: true
      image:
        description: "image name to tag"
        required: true
  push:
    branch: debug
concurrency:
  group: dockerfile-build-${{ inputs.subpath }}
  cancel-in-progress: true
jobs:
  build-dockerfile:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: './.github/actions/dockerfile-ci'
        name: ci
        with:
          subpath: "nas/webdav"
          registry-user: yrct
          registry-password: ${{ secrets.DOCKER_HUB_AUTH }}
          image-name: yrct/webdav
